### PR TITLE
adding debug data for Access Token fetch request

### PR DESCRIPTION
**Pull request by ivzakirov**

### CODE REVIEW

**Comment by jdbrooks** [comment]
Still not receiving a Refresh Token

**Comment by ivzakirov** [comment]
> Still not receiving a Refresh Token

Could you attach the execution log screenshot please? Like this one:
refresh-token

**Comment by jdbrooks** [comment]
[log.txt](https://github.com/jdbrooks/xero-gsheet/files/6853234/log.txt)

**Comment by ivzakirov** [comment]
> [log.txt](https://github.com/jdbrooks/xero-gsheet/files/6853234/log.txt)

Did you apply last [commit](https://github.com/jdbrooks/xero-gsheet/pull/3/commits/3f09bb44ac8577aa8e6f3d1c4cd0ab8fb5c1d823)? It should solve the issue with missing scope and refresh_token.

**Comment by jdbrooks** [comment]
[log2.txt](https://github.com/jdbrooks/xero-gsheet/files/6860033/log2.txt)
Refresh token now appearing.
Running the script after 30 minutes is now working too

**Pull request merged**
